# Generated by Django 5.1.3 on 2024-11-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='p_venta',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='p_costo',
            field=models.FloatField(default=0),
        ),
    ]
