# Generated by Django 5.1.3 on 2024-11-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_producto_p_venta_alter_producto_p_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='p_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='p_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
