# Generated by Django 5.1.3 on 2024-11-27 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_alter_producto_p_costo_alter_producto_p_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='f_fabricacion',
        ),
    ]
